##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt:
    state: latest
    name:
    - python3-venv
    - python3-dev
    - libsm6  # required by opencv
    - libxext6 # required by opencv
    - libxrender-dev # required by opencv
  become: yes

- name: Create app directory
  file:
    path: '{{ app_dir }}'
    state: directory

- name: Create venv directory
  file:
    path: '{{ venv_root }}'
    state: directory

- name: Create the enviroment file for django
  template:
    src: .env.prod
    dest: '{{ env_file }}'
  become: yes

