##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  apt: name={{item}} state=latest
  become: yes
  with_items:
    - python3-venv
    - python3-dev

- name: Create the enviroment file for django
  template:
    src: .env.prod
    dest: '{{ app_api_env}}'
  become: yes

