##
# Update the DNF package cache and install packages as a root user
##
- name: Install required packages
  become: yes
  apt:
    state: latest
    name:
    - python3-venv
    - python3-dev


- name: Create the enviroment file for django
  template:
    src: .env.prod
    dest: '{{ app_api_env}}'
  become: yes

