##
# Set up all the dependencies in a virtualenv required by the Django app
##
- name: Create a virtualenv directory
  file:
    path: '{{ venv_root }}'
    state: directory

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: '{{ venv_dir }}'

- name: Install dependencies
  pip:
    requirements: '{{ app_api_dir }}/requirements.txt'
    virtualenv: '{{ venv_dir }}'
