##
# Run db migrations and get all static files
##
- name: Make migrations
  shell:
    cmd: '. {{ env_file }}; {{ python_bin }} manage.py makemigrations'
    chdir: '{{ app_api_dir }}'

- name: Migrate database
  shell:
    cmd: '. {{ env_file }}; {{ python_bin }} manage.py migrate'
    chdir: '{{ app_api_dir }}'

- name: Build static files
  shell:
    cmd: npm run build:prod
    chdir: '{{ app_spa_dir }}'

- name: Get all static files
  django_manage:
    cmd: '. {{ env_file }}; {{ python_bin }} manage.py collectstatic'
